openapi: 3.0.3
info:
  title: Gravitee.io APIM - Management API - Logs
  description: |
    This API allows to query logs data from the Gravitee.io APIM.

    The API provides access to:
    - **API Logs**: Detailed records of API connections at environment level.

  contact:
    name: DevX team
    email: team-gko@graviteesource.com
    url: https://www.gravitee.io/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: "/management/v2"
    description: APIM Management API v2 - Default base URL
  - url: "/management/v2/organizations/{orgId}"
    description: APIM Management API v2 - Base URL to target specific organizations
    variables:
      orgId:
        description: The unique ID of your organization
        default: DEFAULT

tags:
  - name: logs
    description: Operations related to querying API connection logs

paths:
  /environments/{envId}/logs/search:
    post:
      operationId: searchApiLogs
      summary: Search API logs
      description: |
        Retrieve API logs across the environment.
        Current implementation supports searching for v4 Proxy APIs logs.
      tags:
        - logs
      parameters:
        - $ref: "./openapi-analytics.yaml#/components/parameters/EnvId"
        - $ref: "#/components/parameters/pageParam"
        - $ref: "#/components/parameters/perPageParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchLogsRequest"
            examples:
              filter-by-api-and-http-status:
                summary: Logs for a specific API and HTTP statuses
                value:
                  timeRange:
                    from: "2025-01-01T00:00:00Z"
                    to: "2025-01-31T23:59:59Z"
                  filters:
                    - name: "API"
                      operator: "EQ"
                      value: "7b6ebef3-6236-4ac5-815e-d3dcef83df5d"
                    - name: "HTTP_STATUS"
                      operator: "IN"
                      value:
                        - "200"
                        - "404"
              filter-by-response-time-range:
                summary: Logs filtered by response time range (100ms to 500ms)
                value:
                  timeRange:
                    from: "2025-01-01T00:00:00Z"
                    to: "2025-01-31T23:59:59Z"
                  filters:
                    - name: "RESPONSE_TIME"
                      operator: "GTE"
                      value: 100
                    - name: "RESPONSE_TIME"
                      operator: "LTE"
                      value: 500
              filter-by-entrypoint:
                summary: Logs filtered by entrypoint
                value:
                  timeRange:
                    from: "2025-09-01T00:00:00Z"
                    to: "2026-01-31T23:59:59Z"
                  filters:
                    - name: "ENTRYPOINT"
                      operator: "IN"
                      value:
                        - "native-kafka"
                        - "websocket"
                        - "tcp-proxy"
                        - "sse"
                        - "agent-to-agent"
                        - "mcp-proxy"
                        - "mcp"
                        - "http-post"
                        - "http-proxy"
                        - "webhook"
                        - "llm-proxy"
                        - "http-get"

      responses:
        "200":
          description: List of connection logs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchLogsResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./openapi-analytics.yaml#/components/schemas/Error"

components:
  parameters:
    pageParam:
      name: page
      in: query
      required: false
      description: The page number for pagination.
      schema:
        type: integer
        default: 1
        minimum: 1
    perPageParam:
      name: perPage
      in: query
      required: false
      description: |
        The number of items per page for pagination.
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 100
  schemas:
    SearchLogsRequest:
      type: object
      required:
        - timeRange
      properties:
        timeRange:
          $ref: "./openapi-analytics.yaml#/components/schemas/TimeRange"
        filters:
          type: array
          items:
            $ref: "#/components/schemas/Filter"
          description: Top-level filters

    SearchLogsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/ApiLog"
        pagination:
          $ref: "./openapi-apis.yaml#/components/schemas/Pagination"
        links:
          $ref: "./openapi-apis.yaml#/components/schemas/Links"

    ApiLog:
      type: object
      properties:
        apiId:
          type: string
          description: Id of the API.
          example: 6c530064-0b2c-4004-9300-640b2ce0047b
        timestamp:
          type: string
          format: date-time
          description: The date (as timestamp) of the log.
          example: 2023-05-18T12:40:46.184Z
        id:
          type: string
          description: The internal UUID of the Log.
          example: 00f8c9e7-78fc-4907-b8c9-e778fc790750
        requestId:
          type: string
          description: The id of the request.
          example: 1719d8d1-8d01-48f6-99d8-d18d0178f6d4
        method:
          $ref: "./openapi-apis.yaml#/components/schemas/HttpMethod"
        clientIdentifier:
          type: string
          description: The client identifier of the request.
          example: 12ca17b49af2289436f303e0166030a21e525d266e209267433801a8fd4071a0
        plan:
          $ref: "./openapi-apis.yaml#/components/schemas/BasePlan"
        application:
          $ref: "./openapi-apis.yaml#/components/schemas/BaseApplication"
        transactionId:
          type: string
          description: The id of the transaction.
          example: 00f8c9e7-78fc-4907-b8c9-e778fc790750
        status:
          type: integer
          description: The response's status.
          example: 200
        requestEnded:
          type: boolean
          description: The flag indicating if the request has ended.
          example: true
        gatewayResponseTime:
          type: integer
          description: The response time in ms
          example: 12
        uri:
          type: string
          description: URI of the request.
          example: /my-api
        endpoint:
          type: string
          description: The endpoint URL.
          example: "https://my-api-example.com"
        message:
          type: string
          description: The error message.
          example: "The timeout period of 1000ms has been exceeded"
        errorKey:
          type: string
          description: The error key.
          example: "TIMEOUT_ERROR"
        errorComponentName:
          type: string
          description: The name of the component that generated the error.
          example: "security"
        errorComponentType:
          type: string
          description: The type of the component that generated the error.
          example: "ENDPOINT"
        warnings:
          type: array
          description: The warning diagnostics
          items:
            $ref: "./openapi-apis.yaml#/components/schemas/ApiLogDiagnostic"
        additionalMetrics:
          type: object
          additionalProperties: true
          description: A map of string keys to values

    Filter:
      description: |
        Filters can be used refine the logs results.
      oneOf:
        - $ref: "#/components/schemas/StringFilter"
        - $ref: "#/components/schemas/ArrayFilter"
        - $ref: "#/components/schemas/NumericFilter"
      discriminator:
        propertyName: operator
        mapping:
          EQ: "#/components/schemas/StringFilter"
          IN: "#/components/schemas/ArrayFilter"
          GTE: "#/components/schemas/NumericFilter"
          LTE: "#/components/schemas/NumericFilter"
      example:
        name: "API"
        operator: "EQ"
        value: "7b6ebef3-6236-4ac5-815e-d3dcef83df5d"

    StringFilter:
      description: Filter specification for string values
      type: object
      required: [name, operator, value]
      properties:
        name:
          $ref: "#/components/schemas/FilterName"
        operator:
          $ref: "#/components/schemas/Operator"
        value:
          type: string
          description: Filter value (string for EQ)
      example: { name: "API", operator: "EQ", value: "api-id" }

    ArrayFilter:
      description: Filter specification for array values.
      type: object
      required: [name, operator, value]
      properties:
        name:
          $ref: "#/components/schemas/FilterName"
        operator:
          $ref: "#/components/schemas/Operator"
        value:
          type: array
          items:
            type: string
          description: Filter value (array for IN operator)
      example: { name: "HTTP_STATUS", operator: "IN", value: ["200", "301"] }

    NumericFilter:
      description: Filter specification for numeric values
      type: object
      required: [name, operator, value]
      properties:
        name:
          $ref: "#/components/schemas/FilterName"
        operator:
          $ref: "#/components/schemas/Operator"
        value:
          type: integer
          description: Filter value (number for GTE/LTE)
      example: { name: "RESPONSE_TIME", operator: "GTE", value: 100 }

    FilterName:
      type: string
      enum:
        - API
        - APPLICATION
        - ENTRYPOINT
        - PLAN
        - HTTP_METHOD
        - HTTP_STATUS
        - MCP_METHOD
        - TRANSACTION_ID
        - REQUEST_ID
        - URI
        - RESPONSE_TIME
      description: Available filter names for filtering analytics data

    Operator:
      type: string
      enum:
        - EQ
        - GTE
        - LTE
        - IN
      description: Filter operator
